use_gpu: true
exp_name: ~

dataset: celeba  # mnist / fashion_mnist / celeba
dataroot: ../../data
z_dim: 100

epochs: 20
batch_size: 512

optimizer:
  choice: adam
  adam:
    lr: 0.0006
    betas: [0.5, 0.999]

d_iters: 3
sample_per_epochs: 1
