use_gpu: true
exp_name: ~

dataset: grid25  # ring8 / grid25 / mnist
dataroot: ../../data
z_dim: 32

epochs: 200
batch_size: 256

optimizer:
  choice: adam
  adam:
    lr: 0.0003

d_iters: 5
sample_per_epochs: 2
