use_gpu: true
exp_name: ~

dataset: mnist  # mnist / fashion_mnist
dataroot: ../../data
z_dim: 100

epochs: 50
batch_size: 256

optimizer:
  choice: adam
  adam:
    lr: 0.0002
    betas: [0.5, 0.999]

d_iters: 1
sample_per_epochs: 1
