use_gpu: true
exp_name: ~

dataset: mnist  # ring8 / grid25 / mnist
dataroot: ../../data
z_dim: 100

epochs: 500
batch_size: 256

optimizer:
  choice: rmsprop
  rmsprop:
    lr: 0.00005

clip: [-0.01, 0.01]

d_iters: 1
sample_per_epochs: 5
