use_gpu: true

dataset: mnist  # mnist / fashion_mnist
dataroot: ../data
z_dim: 100
img_size: 64

epochs: 50
batch_size: 512

optimizer:
  choice: adam
  adam:
    lr: 0.0002
    betas: [0, 0.9]

d_iters: 1
sample_per_epochs: 1
