use_gpu: true
exp_name: ~

dataset: mnist  # ring8 / grid25 / mnist
dataroot: ../../data
z_dim: 100

epochs: 300
batch_size: 256

lambda_gp: 10

optimizer:
  choice: adam
  adam:
    lr: 0.0001
    betas: [0.5, 0.9]

d_iters: 5
sample_per_epochs: 3
